export const RULES = Object.freeze({
  SIGNUP_REWARD: 50,
  BASE_VOTE_REWARD: 10,
  REFERRAL_SIGNUP_REWARD: 5,
  REFERRAL_VOTE_REWARD: 2,
  REFERRAL_MIN_ACTIVITY_PERCENT: 80,
  SUGGESTIONS_USERS_THRESHOLD: 10_000,
  EARLY_REWARD_USERS_THRESHOLD: 1_000_000,
  EARLY_VOTERS_LIMIT: 1_000,
  EARLY_VOTER_REWARD: 50,
  PREDICTION_REWARDS_USERS_THRESHOLD: 10_000_000,
  WINNER_REWARD: 8,
  LOSER_REWARD: 2,
  WALLET_USERS_THRESHOLD: 100_000_000,
  DEFAULT_VOTE_DURATION_HOURS: 24,
});

export type Rules = typeof RULES;
